### PR TITLE
Renamed the `print` and `list` commands

### PR DESCRIPTION
**Pull request by babhishek21**
+ `print` command renamed to `list`
+ `list` command renamed to `periods`
Part of fix for #11.

Will make a separate commit for renaming the `rm` command, so that it's easily revertable (if required).

### CODE REVIEW

**Comment by pylipp** [comment]
Thank you, very clean work!
Can you update the Changelog? Please add the `[Incompatible]` flag since different versions of financeager client and webservice don't understand the same set of commands any more.

**Comment by babhishek21** [comment]
> Can you update the Changelog? 

Done ✌️

**Comment by babhishek21** [comment]
Updated the README too. @pylipp I think the quickstart `gif` is outdated now.

**Comment by pylipp** [comment]
Good catch, I'll update it when the `rm` command is renamed.

**Pull request merged**
