### PR TITLE
Fixes #29 - "Remaining" field for print command

### LINKED ISSUE #29: Add a "Remaining" field for the list command
The print command should display a "remaining" field below the total income and expenses.

```
              Earnings                |               Expenses               
Name               Value    Date  ID  | Name               Value    Date  ID 
=============================================================================
Total              000.00             | Total              000.00          
Remaining          0.00
```

### PR DESCRIPTION
**Pull request by IJustDev**
Added the support of a remaining command

### CODE REVIEW

**Comment by IJustDev** [comment]
I'm not sure about the format. Should the remaining field be centered underneath the total values or on one handside?

**Comment by pylipp** [comment]
Thanks for tackling this one so quickly!
First of all, note that there's the `stacked_layout` option for `listing.prettify()` which, if enabled, lays out the earnings and expenses in a stacked way.
```
$ financeager print --stacked-layout
              Earnings               
Name               Value    Date  ID 
Unspecified          100.00          
  Food               100.00 10-12   1

-------------------------------------

              Expenses               
Name               Value    Date  ID 
Einkauf               50.00          
  Einkauf             50.00 10-12   2
Unspecified          500.00          
  Miete, October     500.00 10-12   1
```
So in order to have to have a common implementation for the stacked and the side-by-side layout, I'd suggest you simply append a formatted CategoryEntry to the existing formatted listings (meaning it would be left-aligned when using the side-by-side layout).

For the sake of following TDD, you could first adjust the `test_listing.PrettifyListingsTestCase`, and afterwards adjust the implementation until all tests pass. Did you set up the test environment?

**Comment by pylipp** [comment]
Also I just noticed #35. It's good that you brought up the idea!

**Comment by babhishek21** [comment]
@IJustDev A PR for #11 should be incoming soon. Once that's merged, the `print` command would be renamed to `list`. You might need to pull and rebase your changes post that.

**Comment by pylipp** [comment]
#35 was fixed, please update your branch if this is still relevant :)

**Comment by pylipp** [comment]
I'm not very satisfied with the name 'Remaining' (which suggests a positive value but in case your expenses exceed your earnings, this is not true) - maybe 'Difference' instead, and a minus-sign if negative?

**Comment by IJustDev** [comment]
> 
> 
> I'm not very satisfied with the name 'Remaining' (which suggests a positive value but in case your expenses exceed your earnings, this is not true) - maybe 'Difference' instead, and a minus-sign if negative?

Or maybe "Result"?

**Pull request closed without merging**
